### ISSUE TITLE
Pneumatic piston for intake

### ISSUE THREAD

**Issue by her0me** [Team-5509/PrincessZeta#14]
There is going to be at least one pneumatic piston probably to extend the intake out.  This should be included in the intake command which calls a new intakeExtend command?

**Comment by Shalmezad** [comment]
Can't (well, shouldn't) call commands from other commands.

You'll need to choose one of the following:
* Make a command group and combine the 2 to a button (probably the best option). In this case, the extension would be a separate subsystem.
* Make separate actions/buttons for extend and run intake (most preferred from a programming perspective)
* Throw the solenoid in with the intake subsystem (least preferred)

**Comment by Shalmezad** [comment]
Going to go ahead and assign @KollinBartz since he's doing other work on the intake. Will help avoid conflicts down the line.

**Comment by her0me** [comment]
Hey, Richard how do I do a command group in robot builder

**Comment by Shalmezad** [comment]
Same as command, just different thing. It's the icon with multiple running
people. Pull it in, give it a name, save verify Java.
Then, do your add sequential by hand.

**Comment by her0me** [comment]
I think my addSequential() might be wrong for FoldIntake because I am testing it and it only stays out.  i am quite confident the solenoid is hooked up correctly.

**Comment by her0me** [comment]
I just committed it if you want to look at it

**Comment by her0me** [comment]
got it!

**Comment by her0me** [comment]
Fixed
