### ISSUE TITLE
Field-oriented driving

### ISSUE THREAD

**Issue by her0me** [Team-5509/PrincessZeta#15]
This is when pointing away from you the robot always goes away from you.  This might not be necessary since we shoot on the opposite side of our intake and shouldn't have to turn around much.  This will help for alignment in endgame and control panel.

**Comment by Shalmezad** [comment]
Only works good in drivetrains where any direction is possible. If my robot is facing right, and I point the joystick away from me, how does the robot go away from me?

**Comment by her0me** [comment]
Yeah, that makes sense.   This would work weird never mind.
