### ISSUE TITLE
driveXFeet command (parameterized)

### ISSUE THREAD

**Issue by her0me** [Team-5509/PrincessZeta#18]

**Comment by her0me** [comment]
should take negatives

**Comment by her0me** [comment]
I started following this https://github.com/REVrobotics/SPARK-MAX-Examples/blob/master/Java/Velocity%20Closed%20Loop%20Control/src/main/java/frc/robot/Robot.java is it the right start?

**Comment by her0me** [comment]
I dont know where to go now for this

**Comment by Shalmezad** [comment]
1) You'll need to redo the command in robot builder as presently it's *not* paramaterized. It should take 2 parameters: feet, and max speed.
2) Add a second constructor for just feet, call the other constructor with a speed of 0.3.
3) Create a PIDController in the class. 
4) During `execute()` figure out the feet you've gone based on the encoder ticks (there should be something like frontLeftMotor.getSelectedSensorPosition(), check the docs). 
5) Once you have the ticks you've gone, call pidController.calculate(). One parameter is the feet you've gone, the other is the feet you're trying to reach (the parameter you passed in the constructor). Use the result to feed the motors
6) In isFinished(), return pidController.isAtSetpoint()
7) Make sure to stop the drive train in end() and interrupted().

**Comment by her0me** [comment]
okay, I added everything now, committing now.

**Comment by her0me** [comment]
the setpoint is not setting to the m_feet like I am expecting it to

**Comment by Shalmezad** [comment]
https://github.com/Team-5509/PrincessZeta/blob/master/PrincessZeta2020/src/main/java/frc/robot/commands/DriveXFeet.java#L60
`initialEncoderPosition` needs to be set in `initialize` (when you start the command).

**Comment by Shalmezad** [comment]
https://github.com/Team-5509/PrincessZeta/blob/master/PrincessZeta2020/src/main/java/frc/robot/commands/DriveXFeet.java#L54
DRY (don't repeat yourself). Call `this(feet, 0.5)`.
See [info on constructor chaining](https://www.geeksforgeeks.org/constructor-chaining-java-examples/) for more details.

**Comment by Shalmezad** [comment]
https://github.com/Team-5509/PrincessZeta/blob/master/PrincessZeta2020/src/main/java/frc/robot/commands/DriveXFeet.java#L69
Make sure to call `pidController.reset()` in initialize.

**Comment by Shalmezad** [comment]
During execute(), throw `pidController.getPositionError()` on the smart dashboard to help debugging.

**Comment by Shalmezad** [comment]
https://github.com/Team-5509/PrincessZeta/blob/master/PrincessZeta2020/src/main/java/frc/robot/commands/DriveXFeet.java#L67
Our encoders don't loop, remove `enableContinuousInput` (only for things where max = min, like analog encoders, or gyros where 180 = -180)

**Comment by her0me** [comment]
I reupped the code, It has the stuff we have been throwing on smart dashboard.  the setpoint is stuck at 0.7 when I want it to be 10

**Comment by her0me** [comment]
okay, the continous input thing fixed it

**Comment by her0me** [comment]
How do I set a max speed then?

**Comment by Shalmezad** [comment]
You'll have to manually do it. Pidcontroller calculate will always return
(-1,1). So, if you want it to be (-0.5, 0.5)...

**Comment by her0me** [comment]
ok

**Comment by her0me** [comment]
Ready to test on main robot
