### ISSUE TITLE
Commands for shooter :)

### ISSUE THREAD

**Issue by LikeA5509** [Team-5509/PrincessZeta#4]

**Comment by Shalmezad** [comment]
Take a look at my notes in #12, 

You will want a PID for speed control.
You may want to take a look at some [other code examples](https://github.com/The-Charge/Recharge2020/blob/master/src/main/java/frc/robot/subsystems/Shooter.java).

You're going to want 2 commands:
`ManualShoot`, use the joystick's throttle to determine the speed. Make sure to throw the speed on the smart dashboard. This will help find the values we need for:
`AutoShoot`, use some way to measure distance (Limelight in #9, distance sensor, whatever) to determine the speed automatically.

**Comment by schefferac2020** [comment]
Do you think that air resistance is going to play a significant role in changing the trajectory of the ball?

**Comment by her0me** [comment]
Remember that we are using the CANCoders in a planetary gearbox for this

**Comment by schefferac2020** [comment]
Hey Richard, how do I find the max encoder ticks in Phoenix Tuner? I remember something about plotting values. Thanks.

**Comment by her0me** [comment]
We're staying late btw

**Comment by schefferac2020** [comment]
we are?

**Comment by Shalmezad** [comment]
You have to send the ticks (motor.GetselectedSensorVelocity iirc) to the
smart dashboard.
Once there, you can set it to plot by first adding it (drag from list on
the left), then right click and change display type to plot
