### ISSUE TITLE
LimeLight vision alignment

### ISSUE THREAD

**Issue by her0me** [Team-5509/PrincessZeta#9]

**Comment by Shalmezad** [comment]
You'll need to make a vision target as soon as possible so you can start working on this (either on cardboard or plywood).

First thing you'll want to focus on is getting a distance/angle to the target, and having it available in the code (via network tables) for things like automatically determining the shooting speed (#4)

**Comment by KollinBartz** [comment]
I don't know where to put the code that moves the robot to target the target. her0me also doesn't know. Shalmezad, do you know where I put this code?

**Comment by Shalmezad** [comment]
Make new command, AlignDrivetrainToTarget,
Have it tied to joystick button, while held.
Require Drivetrain subsystem.
In execute (), check Robot.limelight.whateverMethodsYouMake to get data,
see how you need to adjust, and call Robot.drivetrain.drive() to move.

**Comment by KollinBartz** [comment]
We have a rudimentary LimeLight vision alignment system

**Comment by her0me** [comment]
Need to make sure the command can be enabled and disabled with the controller

**Comment by her0me** [comment]
button works while held even though that's not what we were planning it's better that way, so I am gonna leave it.
